app/Http/routes.php
<?php

Route::get('/', function()
{
    return redirect(route('getLogin'));
});

Route::controller('auth', 'Auth\AuthController',
[
    'getLogin'  => 'getLogin',
    'getLogout' => 'logout',
    'postLogin' => 'postLogin',
]);

Route::controller('password', 'Auth\PasswordController',
[
    'getEmail'  => 'getEmail',
    'postEmail' => 'postEmail',
    'getReset'  => 'getReset',
    'postReset'  => 'postReset',
]);

Route::group([ 'middleware' => 'auth' ], function()
{
    Route::group(['middleware' => 'edition'], function(){
        
        //DASHBOARD
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        //LAYOUT
        Route::controller('layout', 'LayoutController',
        [
            'getIndex' => 'layout',
            'postSave' => 'layout.save',
            'getDestroy' => 'layout.destroy',
        ]);

        //PERIODO DE INSCRIÇÃO
        Route::controller('periodo-de-inscricoes', 'PeriodoDeInscricaoController',
        [
            'getIndex' => 'periodo-de-inscricoes',
            'postSave' => 'periodo-de-inscricoes.save',
        ]);

        //USUÁRIOS
        Route::controller('usuarios', 'UsuariosController',
        [
            'getIndex' => 'usuarios',
            'getCreate' => 'usuario.create',
            'getEdit' => 'usuario.edit',
            'postStore' => 'usuario.store',
            'getShow' => 'usuario.show',
            'getActive' => 'usuario.active',
            'getUnactive' => 'usuario.unactive',
        ]);

        Route::put('usuario/{row}', 'UsuariosController@postUpdate')->name('usuario.update');

        Route::delete('usuario/{row}', 'UsuariosController@postDestroy')->name('usuario.destroy');

        //PROFILE
        Route::get('profile', 'ProfileController@getProfile')->name('profile');
        Route::put('profile/save', 'ProfileController@postProfile')->name('profile.save');

        //CADASTRO DE PARTICIPANTES
        Route::controller('cadastro-de-participantes', 'CadastroDeParticipantesController',
        [
            'getIndex' => 'cadastro-de-participantes',
            'postStore' => 'cadastro-de-participantes.store',
        ]);

        //INSCRIÇÕES
        Route::group(['middleware' => 'permissions:inscricoes,inscricoes-opec,inscricoes-participante'], function()
        {
            Route::resource('inscricoes', 'InscricoesController');

            Route::put('inscricoes/{ids}/{user_id}/associar-opec', 'InscricoesController@associarOPEC')->name('inscricoes.associar-opec');
            Route::put('inscricoes/{id}/aprovar', 'InscricoesController@aprovar')->name('inscricoes.aprovar');
            Route::put('inscricoes/{id}/enviar-para-correcao', 'InscricoesController@enviarParaCorrecao')->name('inscricoes.enviar-para-correcao');

            Route::put('inscricoes/{id}/pendente-para-revisao', 'InscricoesController@pendenteParaRevisao')->name('inscricoes.pendente-para-revisao');

            Route::put('inscricoes/{id}/cancelar', 'InscricoesController@cancelar')->name('inscricoes.cancelar');
            Route::put('inscricoes/{id}/validar', 'InscricoesController@validar')->name('inscricoes.validar');
            Route::put('inscricoes/{id}/cancelada-pelo-participante', 'InscricoesController@canceladaPeloParticipante')->name('inscricoes.cancelada-pelo-participante');
            Route::get('inscricoes/{id}/pdf', 'InscricoesController@pdf')->name('inscricoes.pdf');

            Route::get('inscricoes-xls', 'InscricoesController@xls')->name('inscricoes.xls');
            Route::get('inscricoes-csv', 'InscricoesController@csv')->name('inscricoes.csv');
            Route::get('inscricoes/{id}/continuar', 'InscricoesController@continuar')->name('inscricoes.continuar');

            Route::post('inscricoes/upload-peca', 'InscricoesController@uploadPeca')->name('inscricoes.upload-peca');
            Route::post('inscricoes/upload-pi', 'InscricoesController@uploadPI')->name('inscricoes.upload-pi');

            Route::get('inscricoes-imprimir', 'InscricoesController@imprimir')->name('inscricoes.imprimir');

            //Inscrição Profissional
            Route::resource('inscricao-profissional', 'InscricaoProfissionalController');
            Route::post('upload-curriculo','InscricaoProfissionalController@uploadCurriculo')->name('inscricao-profissional.upload-curriculo');
            Route::post('upload-foto','InscricaoProfissionalController@uploadFoto')->name('inscricao-profissional.upload-foto');

            Route::get('inscricoes-profissional-xls', 'InscricaoProfissionalController@xls')->name('inscricoes.profissional.xls');
            Route::get('inscricoes-profissional-csv', 'InscricaoProfissionalController@csv')->name('inscricoes.profissional.csv');
            Route::get('inscricoes-profissional-imprimir', 'InscricaoProfissionalController@imprimir')->name('inscricoes.profissional.imprimir');

            Route::post('inscricao-profissional/{id}/aprovar', 'InscricaoProfissionalController@aprovar')->name('inscricao-profissional.aprovar');
            Route::put('inscricao-profissional/{id}/cancelar','InscricaoProfissionalController@cancelar')->name('inscricao-profissional.cancelar');
            Route::put('inscricao-profissional/{id}/cancelada-pelo-participante', 'InscricaoProfissionalController@canceladaPeloParticipante')->name('inscricao-profissional.cancelada-pelo-participante');

            Route::get('inscricao-profissional/{id}/pdf/{view}', 'InscricaoProfissionalController@pdf')->name('inscricao-profissional.pdf');

            Route::resource('profissional-resultados','ProfissionalResultadoController');
            Route::get('profissional-resultados/{id}/zipper', 'ProfissionalResultadoController@zipper')->name('profissional-resultados.zipper');


        });

        //INSCRIÇÕES DETALHES
        Route::group(['middleware' => 'permissions:log,detalhes-inscricao'], function()
        {
            Route::get('inscricoes/{id}/log', 'InscricoesController@log')->name('inscricoes.log');
            Route::get('inscricoes/{id}/detalhes', 'InscricoesController@log')->name('inscricoes.detalhes');
        });


        //INSCRIÇÕES CATEGORIAS
        Route::resource('categorias', 'CategoriasController');
        Route::get('categorias/{id}/active', 'CategoriasController@active')->name('categorias.active');
        Route::get('categorias/{id}/unactive', 'CategoriasController@unactive')->name('categorias.unactive');

        //INSCRIÇÕES CRITÉRIOS
        Route::resource('criterios', 'CriteriosController');
        Route::get('criterios/{id}/active', 'CriteriosController@active')->name('criterios.active');
        Route::get('criterios/{id}/unactive', 'CriteriosController@unactive')->name('criterios.unactive');

        //INSCRIÇÕES EDICOES
        Route::resource('edicoes', 'EdicoesController');

        Route::get('logs', 'LogsController@index')->name('logs.index');

        //LOG DAS PEÇAS
        Route::get('log-pecas', 'LogPecasController@index')->name('log-pecas.index');

        //JULGAMENTO - Parametrização
        Route::controller('julgamento-parametrizacao', 'JulgamentoParametrizacaoController',
        [
            'getIndex' => 'julgamento-parametrizacao',
            'postSave' => 'julgamento-parametrizacao.save',
        ]);

        //JULGAMENTO TRIAR
        Route::get('julgamento-triar/categorias', 'JulgamentoTriarController@categorias')->name('julgamento-triar.categorias');
        Route::get('julgamento-triar/{id}',       'JulgamentoTriarController@index')->name('julgamento-triar');
        Route::post('julgamento-triar/{id}/save', 'JulgamentoTriarController@save')->name('julgamento-triar.save');

        //JULGAMENTO TRIAGEM
        Route::get('julgamento-triagem/categorias', 'JulgamentoTriagemController@categorias')->name('julgamento-triagem.categorias');
        Route::get('julgamento-triagem/{id}', 'JulgamentoTriagemController@index')->name('julgamento-triagem');

        //DESEMPATAR TRIAGEM
        Route::get('desempatar-triagem/categorias', 'DesempatarTriagemController@categorias')->name('desempatar-triagem.categorias');
        Route::get('desempatar-triagem/{id}', 'DesempatarTriagemController@index')->name('desempatar-triagem');

        Route::post('desempatar-triagem/{id}/confirm-ordenacao', 'DesempatarTriagemController@confirmarOrdenacao')->name('desempatar-triagem.confirm-ordenacao');
        Route::post('desempatar-triagem/{id}/ordernar', 'DesempatarTriagemController@ordenar')->name('desempatar-triagem.ordenar');

        Route::get('desempatar-triagem/{id}/top10', 'DesempatarTriagemController@top10')->name('desempatar-triagem.top10');

        //VER PEÇAS
        Route::get('inscricoes/{id}/ver-pecas', 'VerPecasController@index')->name('inscricoes.pecas');

        //JULGAR - Jurados e Juiz
        Route::get('julgar/categorias', 'JulgarController@categorias')->name('julgar.categorias');
        Route::get('julgar/{id}', 'JulgarController@index')->name('julgar.index');
        Route::post('julgar/{id}/finalizar', 'JulgarController@finalizar')->name('julgar.finalizar');

        //JULGAMENTO - Administrador
        Route::get('julgamento/categorias', 'JulgamentoController@categorias')->name('julgamento.categorias');
        Route::get('julgamento/{id}', 'JulgamentoController@index')->name('julgamento.index');
        Route::post('julgamento/{id}/finalizar', 'JulgamentoController@finalizar')->name('julgamento.finalizar');

        Route::get('julgamento/{id}/top5/{format}', 'DesempatarJulgamentoController@top5')->name('julgamento.top5');
        Route::get('julgamento/resultadogeral/{format}', 'DesempatarJulgamentoController@resultadoGeral')->name('julgamento.resultadogeral');

        Route::get('resultado-edicao', 'EdicoesController@getAgenciasGanhadoras')->name('resultado-edicao');
        Route::get('export', 'EdicoesController@export')->name('edicoes.export');

        //DESEMPATAR JULGAMENTO

resources/views/layouts/partials/panel/sidebar-profissional.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs"><strong class="font-bold">{{ \Auth::user()->name }}</strong></span>
                            <span class="text-muted text-xs block">Opções <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="{{ route('profile') }}">Editar Perfil</a></li>
                        <li class="divider"></li>
                        <li><a href="{{ route('logout') }}"><i class="fa fa-sign-out"></i> Sair</a></li>
                    </ul>
                </div>
            </li>

            <li><a href="{{ route('dashboard') }}"><i class="fa fa-home"></i> <span class="nav-label">Home</span></a></li>

            @can('layout')
            <li><a href="{{ route('layout') }}"><i class="fa fa-picture-o"></i> <span class="nav-label">Layout</span></a></li>
            @endcan

            @can('usuarios')
            <li>
                <a href="{{ route('usuarios') }}"><i class="fa fa-users"></i> <span class="nav-label">Usuários</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="{{ route('usuario.create') }}"><i class="fa fa-plus"></i> Cadastro de usuários</a></li>
                    <li><a href="{{ route('usuarios') }}"><i class="fa fa-th-list"></i> Listagem de usuários</a></li>
                </ul>
            </li>
            @endcan

            @can('cadastro-de-participantes')
            <li><a href="{{ route('cadastro-de-participantes') }}"><i class="fa fa-upload"></i> <span class="nav-label">Cadastro de Participantes</span></a></li>
            @endcan

            @can('inscricoes')
            <li>
                <a href="#"><i class="fa fa-cogs"></i> <span class="nav-label">Parametrização</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    @can('categorias')
                    <li><a href="{{ route('categorias.index') }}"><i class="fa fa-th-list"></i> Categorias</a></li>
                    @endcan

                    @can('edicoes')
                    <li><a href="{{ route('edicoes.index') }}"><i class="fa fa-calendar"></i> Edições</a></li>
                    @endcan

                    @can('inscricoes.parametrizacao')
                    <li><a href="{{ route('periodo-de-inscricoes') }}"><i class="fa fa-calendar"></i> Cadastro das Inscrições</a></li>
                    @endcan
                </ul>
            </li>
            @endcan

            @if(Gate::check('inscricoes') || Gate::check('inscricoes-opec') || Gate::check('inscricoes-participante'))
                <li>
                    <a href="#"><i class="fa fa-users"></i></i> <span class="nav-label">Inscrições</span> <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        @if($periodoDeInscricao && Gate::check('inscricoes-participante'))
                            <li><a href="{{ route('inscricao-profissional.create') }}"><i class="fa fa-plus"></i> Nova Inscrição</a></li>
                        @endif
                        <li><a href="{{ route('inscricao-profissional.index') }}"><i class="fa fa-list"></i> Inscrições</a></li>
                    </ul>
                </li>
            @endif

            @if(Gate::check('inscricoes'))
                <li>
                    <a href="{{ route('profissional-resultados.index') }}"><i class="fa fa-gavel"></i> <span class="nav-label">Resultados</span> </a>
                </li>
            @endif


            @if(Gate::check('resultado-edicao'))
                @can('resultado-edicao')
                <li><a href="{{ route('resultado-edicao') }}"><i class="fa fa-download"></i> <span class="nav-label">Resultado por Agência</span></a></li>
                @endcan
            @endif

        </ul>
    </div>
</nav>

resources/views/layouts/partials/panel/sidebar.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs"><strong class="font-bold">{{ \Auth::user()->name }}</strong></span>
                            <span class="text-muted text-xs block">Opções <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="{{ route('profile') }}">Editar Perfil</a></li>
                        <li class="divider"></li>
                        <li><a href="{{ route('logout') }}"><i class="fa fa-sign-out"></i> Sair</a></li>
                    </ul>
                </div>
            </li>
            
            <li><a href="{{ route('dashboard') }}"><i class="fa fa-home"></i> <span class="nav-label">Home</span></a></li>

            @can('layout')
            <li><a href="{{ route('layout') }}"><i class="fa fa-picture-o"></i> <span class="nav-label">Layout</span></a></li>
            @endcan

            @can('usuarios')
            <li>
                <a href="{{ route('usuarios') }}"><i class="fa fa-users"></i> <span class="nav-label">Usuários</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="{{ route('usuario.create') }}"><i class="fa fa-plus"></i> Cadastro de usuários</a></li>
                    <li><a href="{{ route('usuarios') }}"><i class="fa fa-th-list"></i> Listagem de usuários</a></li>
                </ul>
            </li>
            @endcan

            @can('cadastro-de-participantes')
            <li><a href="{{ route('cadastro-de-participantes') }}"><i class="fa fa-upload"></i> <span class="nav-label">Cadastro de Participantes</span></a></li>
            @endcan

            @can('inscricoes')
            <li>
                <a href="#"><i class="fa fa-cogs"></i> <span class="nav-label">Parametrização</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    @can('categorias')
                    <li><a href="{{ route('categorias.index') }}"><i class="fa fa-th-list"></i> Categorias</a></li>
                    @endcan

                    @can('criterios')
                        <li><a href="{{ route('criterios.index') }}"><i class="fa fa-check-square-o"></i> Critérios</a></li>
                    @endcan

                    @can('edicoes')
                        <li><a href="{{ route('edicoes.index') }}"><i class="fa fa-calendar"></i> Edições</a></li>
                    @endcan

                    @can('inscricoes.parametrizacao')
                    <li><a href="{{ route('periodo-de-inscricoes') }}"><i class="fa fa-calendar"></i> Cadastro das Inscrições</a></li>
                    @endcan

                    @can('julgamento.parametrizacao')
                    <li><a href="{{ route('julgamento-parametrizacao') }}"><i class="fa fa-calendar"></i> Julgamento</a></li>
                    @endcan
                </ul>
            </li>
            @endcan

            @if(Gate::check('inscricoes') || Gate::check('inscricoes-opec') || Gate::check('inscricoes-participante'))
            <li>
                <a href="#"><i class="fa fa-users"></i></i> <span class="nav-label">Inscrições</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    @if($periodoDeInscricao && Gate::check('inscricoes-participante'))
                    <li><a href="{{ route('inscricoes.create') }}"><i class="fa fa-plus"></i> Nova Inscrição</a></li>
                    @endif
                    <li><a href="{{ route('inscricoes.index') }}"><i class="fa fa-list"></i> Inscrições</a></li>
                </ul>
            </li>
            @endif

            @if(Gate::check('inscricoes') || Gate::check('inscricoes-opec'))
            <li>
                <a href="*"><i class="fa fa-history"></i> <span class="nav-label">Logs</span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="{{ route('log-pecas.index') }}"><i class="fa fa-list"></i>Log de Peças</a></li>
                    
                    <li><a href="{{ route('logs.index') }}"><i class="fa fa-list"></i>Logs do Sistema</a></li>
                </ul>
            </li>
            @endif

            @if(
                Gate::check('julgamento.triar')
                || Gate::check('julgamento.triagem')
                || Gate::check('julgamento.triagem.desempatar')
                || Gate::check('julgar')
                || Gate::check('julgamento')
                || Gate::check('julgamento.desempatar')
            )
            <li>
                <a href="#"><i class="fa fa-gavel"></i> <span class="nav-label">Julgamento</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    @can('julgamento.triar')
                    <li><a href="{{ route('julgamento-triar.categorias') }}"><i class="fa fa-list"></i> Triar</a></li>
                    @endcan

                    @can('julgamento.triagem')
                    <li><a href="{{ route('julgamento-triagem.categorias') }}"><i class="fa fa-list"></i> Triagem</a></li>
                    @endcan

                    @can('julgamento.triagem.desempatar')
                    <li><a href="{{ route('desempatar-triagem.categorias') }}"><i class="fa fa-list"></i> Desempatar Triagem</a></li>
                    @endcan

                    @can('julgar')
                    <li><a href="{{ route('julgar.categorias') }}"><i class="fa fa-list"></i> Julgar</a></li>
                    @endcan

                    @can('julgamento')
                    <li><a href="{{ route('julgamento.categorias') }}"><i class="fa fa-list"></i> Julgamento</a></li>
                    @endcan

                    @can('julgamento.desempatar')
                    <li><a href="{{ route('desempatar-julgamento.categorias') }}"><i class="fa fa-list"></i> Desempatar</a></li>
                    @endcan
                </ul>
            </li>
            @if(Gate::check('resultado-edicao'))
                @can('resultado-edicao')
                     <li><a href="{{ route('resultado-edicao') }}"><i class="fa fa-download"></i> <span class="nav-label">Resultado por Agência</span></a></li>
                @endcan
            @endif
            @endif
        </ul>
    </div>
</nav>